# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-26 23:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20191026_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShuffleItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Song')),
            ],
        ),
    ]
