# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-27 09:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_shuffleitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('token', models.TextField(primary_key=True, serialize=False)),
                ('address', models.GenericIPAddressField()),
                ('lastUsed', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='displayName',
        ),
        migrations.AddField(
            model_name='user',
            name='salt',
            field=models.TextField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='authtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.User'),
        ),
    ]
