# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-27 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skype', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skypeconfig',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
